Zadaca5/urls.py
from django.contrib import admin
from django.urls import path
from jetkoSilver.views import *
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('',jewellery, name="jewellery"),
                  path('jewellery/', jewellery, name="jewelries"),
                  path('jewellery_details/<int:jewellery_id>/', jewellery_details, name="jewellery_details"),
                  path('cart_items/', cart_items, name="cart_items"),
                  path('checkout/', checkout, name="checkout"),
                  path('final_site/', final_site, name="final_site"),
                  path('register/', register, name='register'),
                  path('login/', user_login, name='login'),
                  path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
                  path('item/delete/<int:item_id>/', delete_item, name='delete_item'),
                  path('item/add/', add_item, name='add_item'),
                  path('edit_item/<int:item_id>/', edit_item, name='edit_item'),
                  path('cart/item/delete/<int:item_id>/', delete_cart_item, name='delete_cart_item'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jetkoSilver/models.py
from django.contrib.auth.models import User
from django.db import models


class UserInformation(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)

    class Meta:
        verbose_name_plural = "User's information"

    def __str__(self) -> str:
        return f"({self.user!r})"


class Product(models.Model):
    name = models.CharField(max_length=100)
    brand = models.CharField(max_length=100)
    description = models.TextField()
    material = models.CharField(max_length=100)
    color = models.CharField(max_length=100)
    jewelry_type = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.IntegerField()
    image = models.ImageField(upload_to="images/")
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Product informations"

    def __str__(self):
        return self.name


class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Cart for {self.user.username}"


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"{self.product} ({self.quantity}) in Cart"


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.SET_NULL, null=True)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    country = models.CharField(max_length=50)
    city_postal = models.CharField(max_length=50)
    shipping_address = models.CharField(max_length=50)
    phone_number = models.CharField(max_length=50)
    pay_with_card = models.BooleanField(default=True)

    def __str__(self):
        return f"Order #{self.pk} by {self.user}"

    def calculate_total_amount(self):
        total = 0
        cart_items = self.cart.items.all()
        for cart_item in cart_items:
            total += cart_item.product.price * cart_item.quantity
        return total

jetkoSilver/forms.py
from django import forms
from .models import *


class ItemForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'color', 'jewelry_type', 'material', 'description', 'price', 'quantity', 'image']


class CheckoutForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['country', 'city_postal', 'shipping_address', 'phone_number', 'pay_with_card']
        labels = {
            'country': 'Country',
            'city_postal': 'City / Postal',
            'shipping_address': 'Shipping Address',
            'phone_number': 'Phone Number',
            'pay_with_card': 'Pay with Card',
        }
        widgets = {
            'pay_with_card': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }

jetkoSilver/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from .forms import CheckoutForm, ItemForm


def jewellery(request):
    query = request.GET.get('search_query', '')
    jewelry_type = request.GET.getlist('jewelry_type')
    material = request.GET.getlist('material')
    color = request.GET.getlist('color')
    all_jewelries = Product.objects.all()

    if query:
        all_jewelries = all_jewelries.filter(jewelry_type_icontains=query)

    if jewelry_type:
        all_jewelries = all_jewelries.filter(jewelry_type__in=jewelry_type)

    if material:
        all_jewelries = all_jewelries.filter(material__in=material)

    if color:
        all_jewelries = all_jewelries.filter(color__in=color)

    return render(request, 'jewellery.html',
                  {'jewellery': all_jewelries, 'query': query, 'selected_jewelry_type': jewelry_type,
                   'selected_material': material,
                   'selected_color': color, 'user': request.user})


@login_required(login_url='login')
def jewellery_details(request, jewellery_id):
    jewellery = get_object_or_404(Product, id=jewellery_id)
    cart, created = Cart.objects.get_or_create(user=request.user)

    if request.method == 'POST':
        quantity = int(request.POST.get('quantity', 1))
        # Check if the purchased quantity is available
        if quantity <= jewellery.quantity:
            cart_item, created = CartItem.objects.get_or_create(cart=cart, product=jewellery)
            cart_item.quantity = quantity
            cart_item.save()
            return redirect('cart_items')
        else:
            return HttpResponse("Insufficient quantity available")
    return render(request, 'jewellery_details.html', {'jewellery': jewellery})


@login_required
def delete_item(request, item_id):
    item = get_object_or_404(Product, id=item_id)
    item.delete()
    return redirect('jewellery')


@login_required
def edit_item(request, item_id):
    item = get_object_or_404(Product, id=item_id)
    if request.method == 'POST':
        form = ItemForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            return redirect('jewellery_details', jewellery_id=item.id)
    else:
        form = ItemForm(instance=item)
    return render(request, 'edit_product.html', {'form': form, 'item': item})


@login_required
def add_item(request):
    if request.method == 'POST':
        form = ItemForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('jewellery_details',
                            jewellery_id=form.save().id)  # Redirect to the cart or any other appropriate URL
    else:
        form = ItemForm()
    return render(request, 'add_product.html', {'form': form})


@login_required(login_url='login')
def cart_items(request):
    items = CartItem.objects.filter(cart__user=request.user)
    cart_total = sum(item.product.price * item.quantity for item in items)
    context = {'cart_items': items, 'total': cart_total}
    return render(request, 'cart_items.html', context)


@login_required
def delete_cart_item(request, item_id):
    item = get_object_or_404(CartItem, id=item_id)
    item.delete()
    return redirect('cart_items')


@login_required(login_url='login')
def checkout(request):
    if request.method == 'POST':
        form = CheckoutForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            order.user = request.user
            order.cart = request.user.cart  # Assuming you have associated each user with a cart
            order.total_amount = order.calculate_total_amount()  # Calculate the total amount
            order.save()
            # Subtract the purchased quantities from the products' quantities
            items = order.cart.items.all()
            for cart_item in items:
                cart_item.product.quantity -= cart_item.quantity
                cart_item.product.save()
            # Clear the cart items
            request.user.cart.items.all().delete()
            # Redirect or render success page
            return redirect('final_site')
        # else:
        #     return redirect('cases')
    else:
        form = CheckoutForm()
    context = {'form': form}
    return render(request, 'checkout.html', context)


@login_required(login_url='login')
def final_site(request):
    return render(request, 'final_site.html')


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = UserCreationForm()
    return render(request, 'register.html', {'form': form})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('jewellery')
        else:
            # Handle invalid login credentials
            return render(request, 'login.html', {'error': 'Invalid login credentials.'})
    return render(request, 'login.html')

jetkoSilver/templates/add_product.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Jetko Silver</title>
    <link rel="icon" type="image/x-icon" href="https://freepngimg.com/download/phone_case/33082-2-phone-case-photos.png">
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
<style>
      body {
            background-color: #f1f1f1;
        }
</style>
</head>
<body class="container">
{% include 'header.html' %}<hr>
<h3 class="mt-4">Add New Item:</h3>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
    <button type="submit" class="btn btn-primary mb-5">Add Item</button>
</form>
</body>
</html>

jetkoSilver/templates/cart_items.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Jetko Silver</title>
    <link rel="icon" type="image/x-icon" href="https://freepngimg.com/download/phone_case/33082-2-phone-case-photos.png">
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <style>
        .btn-danger:hover{
            background-color: black !important;
        }
         body {
            background-color: #f1f1f1;
        }
    </style>
</head>
<body class="container">
{% include 'header.html' %}<hr>
{% block content %}
  <h3 class="mt-5">Cart Items: </h3>
  {% if cart_items %}
    <table class="table">
  <thead>
    <tr>
        <th scope="col">Picture</th>
      <th class="text-center" scope="col">Name</th>
      <th class="text-center" scope="col">Quantity</th>
      <th class="text-center" scope="col">Price</th>
        <th></th>
    </tr>
  </thead>
  <tbody>
     {% for item in cart_items %}
         <tr>
             <th scope="row"><img src="{{ MEDIA_URL }}{{ item.product.image.url }}" class="" style="height: 150px; width: 70px; "></th>
             <td class="fs-5 text-center">{{ item.product.name }}</td>
             <td class="fs-5 text-center">{{ item.quantity }}</td>
             <td class="fs-5 text-center">{{ item.product.price }} $</td>
             <td>
                 <form action="{% url 'delete_cart_item' item.id %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Delete</button>
                  </form>
                </td>
         </tr>
      {% endfor %}
    <tr>
  </tbody>
</table>
  {% else %}
    <p>Your cart is empty.</p>
  {% endif %}
{% endblock %}
<h2 class="d-inline">Total Price:</h2>
<h2 class="d-inline">{{ total }} $</h2>

<a href="{% url 'checkout' %}" class="d-flex text-decoration-none mt-3">
    <button id="button" class="btn btn-danger rounded-pill px-4 py-2 fw-bold fs-4 text-white">Continue to checkout</button>
</a>
</body>
</html>

jetkoSilver/templates/checkout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <title>SupCase</title>
    <link rel="icon" type="image/x-icon" href="https://freepngimg.com/download/phone_case/33082-2-phone-case-photos.png">
    <style>
        button:hover{
            color: white!important;
        }
         body {
            background-color: #f1f1f1;
        }
    </style>
</head>
<body>
<div class="container justify-content-center mt-5">
{% include 'header.html' %}<hr>
    <h3 class="mt-5 mb-3">Please leave us information for delivery</h3>
    <form method="POST" action="{% url 'checkout' %}">
      {% csrf_token %}
        {{ form.errors }}
      <div class="mb-3">
        {{ form.country.label_tag }}
        {{ form.country }}
      </div>

      <div class="mb-3">
        {{ form.city_postal.label_tag }}
        {{ form.city_postal }}
      </div>

      <div class="mb-3">
        {{ form.shipping_address.label_tag }}
        {{ form.shipping_address }}
      </div>

      <div class="mb-3">
        {{ form.phone_number.label_tag }}
        {{ form.phone_number }}
      </div>
      <div class="mb-3">
        {{ form.pay_with_card }}
        {{ form.pay_with_card.label_tag }}
        <p>You can unselect this to <strong>pay on delivery!</strong></p>
      </div>

        <div class="mb-3 ">
            <span>Card number: </span><input type="text" class="mt-4" id="card_number" ><br>
            <span>Expiration date: </span><input type="text" class="mt-4" id="ex_date"><br>
            <span>CVV: </span><input type="text" class="mt-4" id="cvv"><br>
      </div>
      <button type="submit" class="btn rounded-pill px-3 py-1 fw-bold fs-5"  style="background-color: indianred">Place Order</button>
    </form>

</div>

</body>
<script>
  var payWithCardInput = document.querySelector('#id_pay_with_card');
  var cardNumberInput = document.querySelector('#card_number');
  var expirationDateInput = document.querySelector('#ex_date');
  var cvvInput = document.querySelector('#cvv');

  // Function to toggle the required attribute
  function toggleRequiredAttribute() {
    if (payWithCardInput.checked) {
      cardNumberInput.required = true;
      expirationDateInput.required = true;
      cvvInput.required = true;
    } else {
      cardNumberInput.required = false;
      expirationDateInput.required = false;
      cvvInput.required = false;
    }
  }

  // Add event listener to toggle required attribute on change
  payWithCardInput.addEventListener('change', toggleRequiredAttribute);
  // Initial check on page load
  toggleRequiredAttribute();
</script>

</html>

jetkoSilver/templates/edit_product.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <title>Jetko SIlver</title>
    <link rel="icon" type="image/x-icon" href="https://freepngimg.com/download/phone_case/33082-2-phone-case-photos.png">
    <style>
         body {
            background-color: #f1f1f1;
        }
    </style>
</head>
<body class="container">
{% include 'header.html' %}<hr>
{% block content %}
    <div class="mt-4">
          <h2>Edit Item</h2>
          <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary mb-5">Update Item</button>
          </form>
    </div>
{% endblock %}
</body>
</html>

jetkoSilver/templates/final_site.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Jetko Silver</title>
    <link rel="icon" type="image/x-icon" href="https://freepngimg.com/download/phone_case/33082-2-phone-case-photos.png">
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <style>
    body {
      background-color: #f5f5f5;
      padding: 20px;
    }

    .container {
      max-width: 550px;
      margin: 0 auto;
      text-align: center;
      background-color: #fff;
      border-radius: 5px;
      padding: 20px;
    }
    a:hover{
        color: white;
    }
  </style>
</head>
<body>

<div class="container mt-5">
    <h1 class="fs-1">Congratulations!</h1>
    <p class="fs-4">You have successfully made your order. You will receive your order in 7 days.</p>
    <a href="{% url 'jewellery' %}">
        <button class="btn rounded-pill px-3 py-1 fw-bold fs-5" style="background-color: indianred">Back to home page</button>
    </a>
</div>
</body>
</html>

jetkoSilver/templates/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Jetko Silver</title>
    <link rel="icon" type="images/x-icon" href="https://freepngimg.com/download/phone_case/33082-2-phone-case-photos.png">
</head>
<body>
    <div class="row mt-5">
         <a href="{% url 'jewellery' %}" class="col-3 fw-bold text-decoration-none" style="color: #444F5A">
             <h1 class="mb-0">Jetko Silver</h1>
         </a>
        <div class="col-9 text-end">
            {% if user.is_authenticated and user.is_superuser %}
                <a href="{% url 'add_item' %}" class="btn btn-primary me-3">Add New Item</a>
            {% endif %}
            {% if user.is_authenticated %}
                <a href="{% url 'cart_items' %}" class="text-decoration-none">
                    <h4 style="color: #444F5A" class="d-inline me-3">MyCart</h4>
                </a>
                <a href="{% url 'logout' %}" class="text-decoration-none">
                    <h4 style="color: #444F5A" class="d-inline">LogOut</h4>
                </a>
            {% else %}
                <a href="{% url 'login' %}" class="text-decoration-none">
                        <h4 style="color: #444F5A" class="d-inline">LogIn</h4>
                </a>
            {% endif %}
        </div>
    </div>
</body>
</html>

jetkoSilver/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Jetko Silver</title>
    <link rel="icon" type="image/x-icon" href="https://freepngimg.com/download/phone_case/33082-2-phone-case-photos.png">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>

</head>
<body class="container">
<div class="row justify-content-center mt-5">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h2>Login</h2>
                </div>
                <div class="card-body">
                    {% if error %}
                        <div class="alert alert-danger" role="alert">
                            {{ error }}
                        </div>
                    {% endif %}
                    <form method="post">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="username" class="form-label">Username</label>
                            <input type="text" class="form-control" id="username" name="username">
                        </div>
                        <div class="mb-3">
                            <label for="password" class="form-label">Password</label>
                            <input type="password" class="form-control" id="password" name="password">
                        </div>
                        <button type="submit" class="btn btn-primary">Login</button>
                    </form>
                    <div class="mt-3 text-center">
                        Don't have an account? <a href="{% url 'register' %}">Create an account</a>
                    </div>
                </div>
            </div>
        </div>
    </div>




{#{% block content %}#}
{#  <h2>Login</h2>#}
{#  {% if error %}#}
{#    <div class="alert alert-danger" role="alert">#}
{#      {{ error }}#}
{#    </div>#}
{#  {% endif %}#}
{#  <form method="post">#}
{#    {% csrf_token %}#}
{#    <div class="mb-3">#}
{#      <label for="username" class="form-label">Username</label>#}
{#      <input type="text" class="form-control" id="username" name="username">#}
{#    </div>#}
{#    <div class="mb-3">#}
{#      <label for="password" class="form-label">Password</label>#}
{#      <input type="password" class="form-control" id="password" name="password">#}
{#    </div>#}
{#    <button type="submit" class="btn btn-primary">Login</button>#}
{#  </form>#}
{#{% endblock %}#}
</body>
</html>

jetkoSilver/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Jetko Silver</title>
    <link rel="icon" type="image/x-icon" href="https://freepngimg.com/download/phone_case/33082-2-phone-case-photos.png">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>

</head>
<body class="container">
<div class="row justify-content-center mt-5">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h2>Register</h2>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="mb-3">
                                <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                                {{ field }}
                            </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-primary">Register</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{##}
{##}
{#{% block content %}#}
{#  <h2>Register</h2>#}
{#  <form method="post">#}
{#    {% csrf_token %}#}
{#    {{ form.as_p }}#}
{#    <button type="submit" class="btn btn-primary">Register</button>#}
{#  </form>#}
{#{% endblock %}#}

</body>
</html>